name: smartpulse_app
description: Aplicación de alertas inteligentes para inclusión laboral
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Bluetooth Low Energy (versión estable)
  flutter_blue_plus: ^1.32.0
  
  # Almacenamiento local
  shared_preferences: ^2.2.2
  
  # Permisos
  permission_handler: ^11.3.0
  
  # Iconos Material
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Recursos de la app
  assets:
    - assets/images/logo.png